/**
 * This class is designed to be an extension to the CaseEmailAttachmentsAction 
 * custom publisher action. For the most part, it is here in order to provide
 * RemoteAction methods to the Angular Application on the page.
 *
 * @author Cloud Performer <cgary@cloudperformer.com>
 * @version 1.0
 **/ 
public with sharing class CaseEmailAttachmentsActionExt {
    /**
     * Constructor
     **/
    public CaseEmailAttachmentsActionExt() {

    }
    /**
     * Constructor
     **/
    public CaseEmailAttachmentsActionExt(ApexPages.StandardController stdCon){

    }
}
